import './globals.css'
import Footer from './components/Footer/Footer'
import Header from './components/Header/Header'

export const metadata = {
  title: 'Bistro',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header />
      <main >{children}</main>
      <Footer />
    </html>
  )
}
